// Generated by Haxe 4.3.1
#ifndef INCLUDED_Player
#define INCLUDED_Player

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS0(Player)
HX_DECLARE_CLASS0(WorldMap)
HX_DECLARE_CLASS1(algorithm,PriorityQueue)
HX_DECLARE_CLASS1(haxe,IMap)
HX_DECLARE_CLASS2(haxe,ds,StringMap)



class HXCPP_CLASS_ATTRIBUTES Player_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef Player_obj OBJ_;
		Player_obj();

	public:
		enum { _hx_ClassId = 0x33e526a5 };

		void __construct( ::WorldMap world);
		inline void *operator new(size_t inSize, bool inContainer=true,const char *inName="Player")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,true,"Player"); }
		static ::hx::ObjectPtr< Player_obj > __new( ::WorldMap world);
		static ::hx::ObjectPtr< Player_obj > __alloc(::hx::Ctx *_hx_ctx, ::WorldMap world);
		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~Player_obj();

		HX_DO_RTTI_ALL;
		::hx::Val __Field(const ::String &inString, ::hx::PropertyAccess inCallProp);
		static bool __GetStatic(const ::String &inString, Dynamic &outValue, ::hx::PropertyAccess inCallProp);
		::hx::Val __SetField(const ::String &inString,const ::hx::Val &inValue, ::hx::PropertyAccess inCallProp);
		static bool __SetStatic(const ::String &inString, Dynamic &ioValue, ::hx::PropertyAccess inCallProp);
		void __GetFields(Array< ::String> &outFields);
		static void __register();
		void __Mark(HX_MARK_PARAMS);
		void __Visit(HX_VISIT_PARAMS);
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("Player",81,5f,4d,6c); }

		static void __boot();
		static  ::haxe::ds::StringMap priorities;
		int x;
		int y;
		int sight;
		int level;
		 ::WorldMap world;
		::String facing;
		::String _hx___directory;
		::Array< ::String > _hx___directions;
		 ::algorithm::PriorityQueue _hx___rockQueue;
		void pathMovement();
		::Dynamic pathMovement_dyn();

		void mapOut();
		::Dynamic mapOut_dyn();

		void scanArea();
		::Dynamic scanArea_dyn();

		void command(::String cmd);
		::Dynamic command_dyn();

};


#endif /* INCLUDED_Player */ 
