// Generated by Haxe 4.3.1
#include <hxcpp.h>

#ifndef INCLUDED_algorithm_Node
#include <algorithm/Node.h>
#endif
#ifndef INCLUDED_haxe_ds_GenericCell_algorithm_Node
#include <haxe/ds/GenericCell_algorithm_Node.h>
#endif
#ifndef INCLUDED_haxe_ds_GenericStack_algorithm_Node
#include <haxe/ds/GenericStack_algorithm_Node.h>
#endif
#ifndef INCLUDED_haxe_ds__GenericStack_GenericStackIterator_algorithm_Node
#include <haxe/ds/_GenericStack/GenericStackIterator_algorithm_Node.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_7340535acf258a1e_107_new,"haxe.ds.GenericStack_algorithm_Node","new",0x37902c7b,"haxe.ds.GenericStack_algorithm_Node.new","/usr/local/lib/haxe/std/haxe/ds/GenericStack.hx",107,0xcaed4b39)
HX_LOCAL_STACK_FRAME(_hx_pos_7340535acf258a1e_113_add,"haxe.ds.GenericStack_algorithm_Node","add",0x37864e3c,"haxe.ds.GenericStack_algorithm_Node.add","/usr/local/lib/haxe/std/haxe/ds/GenericStack.hx",113,0xcaed4b39)
HX_LOCAL_STACK_FRAME(_hx_pos_7340535acf258a1e_122_first,"haxe.ds.GenericStack_algorithm_Node","first",0xc4bd510b,"haxe.ds.GenericStack_algorithm_Node.first","/usr/local/lib/haxe/std/haxe/ds/GenericStack.hx",122,0xcaed4b39)
HX_LOCAL_STACK_FRAME(_hx_pos_7340535acf258a1e_130_pop,"haxe.ds.GenericStack_algorithm_Node","pop",0x3791b9ac,"haxe.ds.GenericStack_algorithm_Node.pop","/usr/local/lib/haxe/std/haxe/ds/GenericStack.hx",130,0xcaed4b39)
HX_LOCAL_STACK_FRAME(_hx_pos_7340535acf258a1e_144_isEmpty,"haxe.ds.GenericStack_algorithm_Node","isEmpty",0xfacbe3de,"haxe.ds.GenericStack_algorithm_Node.isEmpty","/usr/local/lib/haxe/std/haxe/ds/GenericStack.hx",144,0xcaed4b39)
HX_LOCAL_STACK_FRAME(_hx_pos_7340535acf258a1e_156_remove,"haxe.ds.GenericStack_algorithm_Node","remove",0xdc468309,"haxe.ds.GenericStack_algorithm_Node.remove","/usr/local/lib/haxe/std/haxe/ds/GenericStack.hx",156,0xcaed4b39)
HX_LOCAL_STACK_FRAME(_hx_pos_7340535acf258a1e_178_iterator,"haxe.ds.GenericStack_algorithm_Node","iterator",0x43b32bf3,"haxe.ds.GenericStack_algorithm_Node.iterator","/usr/local/lib/haxe/std/haxe/ds/GenericStack.hx",178,0xcaed4b39)
HX_LOCAL_STACK_FRAME(_hx_pos_7340535acf258a1e_203_toString,"haxe.ds.GenericStack_algorithm_Node","toString",0xe887b2b1,"haxe.ds.GenericStack_algorithm_Node.toString","/usr/local/lib/haxe/std/haxe/ds/GenericStack.hx",203,0xcaed4b39)
namespace haxe{
namespace ds{

void GenericStack_algorithm_Node_obj::__construct(){
            	HX_STACKFRAME(&_hx_pos_7340535acf258a1e_107_new)
            	}

Dynamic GenericStack_algorithm_Node_obj::__CreateEmpty() { return new GenericStack_algorithm_Node_obj; }

void *GenericStack_algorithm_Node_obj::_hx_vtable = 0;

Dynamic GenericStack_algorithm_Node_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< GenericStack_algorithm_Node_obj > _hx_result = new GenericStack_algorithm_Node_obj();
	_hx_result->__construct();
	return _hx_result;
}

bool GenericStack_algorithm_Node_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x0c965727;
}

void GenericStack_algorithm_Node_obj::add( ::algorithm::Node item){
            	HX_GC_STACKFRAME(&_hx_pos_7340535acf258a1e_113_add)
HXDLIN( 113)		this->head =  ::haxe::ds::GenericCell_algorithm_Node_obj::__alloc( HX_CTX ,item,this->head);
            	}


HX_DEFINE_DYNAMIC_FUNC1(GenericStack_algorithm_Node_obj,add,(void))

 ::algorithm::Node GenericStack_algorithm_Node_obj::first(){
            	HX_STACKFRAME(&_hx_pos_7340535acf258a1e_122_first)
HXDLIN( 122)		if (::hx::IsNull( this->head )) {
HXDLIN( 122)			return null();
            		}
            		else {
HXDLIN( 122)			return this->head->elt;
            		}
HXDLIN( 122)		return null();
            	}


HX_DEFINE_DYNAMIC_FUNC0(GenericStack_algorithm_Node_obj,first,return )

 ::algorithm::Node GenericStack_algorithm_Node_obj::pop(){
            	HX_STACKFRAME(&_hx_pos_7340535acf258a1e_130_pop)
HXLINE( 131)		 ::haxe::ds::GenericCell_algorithm_Node k = this->head;
HXLINE( 132)		if (::hx::IsNull( k )) {
HXLINE( 133)			return null();
            		}
            		else {
HXLINE( 135)			this->head = k->next;
HXLINE( 136)			return k->elt;
            		}
HXLINE( 132)		return null();
            	}


HX_DEFINE_DYNAMIC_FUNC0(GenericStack_algorithm_Node_obj,pop,return )

bool GenericStack_algorithm_Node_obj::isEmpty(){
            	HX_STACKFRAME(&_hx_pos_7340535acf258a1e_144_isEmpty)
HXDLIN( 144)		return ::hx::IsNull( this->head );
            	}


HX_DEFINE_DYNAMIC_FUNC0(GenericStack_algorithm_Node_obj,isEmpty,return )

bool GenericStack_algorithm_Node_obj::remove( ::algorithm::Node v){
            	HX_STACKFRAME(&_hx_pos_7340535acf258a1e_156_remove)
HXLINE( 157)		 ::haxe::ds::GenericCell_algorithm_Node prev = null();
HXLINE( 158)		 ::haxe::ds::GenericCell_algorithm_Node l = this->head;
HXLINE( 159)		while(::hx::IsNotNull( l )){
HXLINE( 160)			if (::hx::IsInstanceEq( l->elt,v )) {
HXLINE( 161)				if (::hx::IsNull( prev )) {
HXLINE( 162)					this->head = l->next;
            				}
            				else {
HXLINE( 164)					prev->next = l->next;
            				}
HXLINE( 165)				goto _hx_goto_5;
            			}
HXLINE( 167)			prev = l;
HXLINE( 168)			l = l->next;
            		}
            		_hx_goto_5:;
HXLINE( 170)		return ::hx::IsNotNull( l );
            	}


HX_DEFINE_DYNAMIC_FUNC1(GenericStack_algorithm_Node_obj,remove,return )

 ::Dynamic GenericStack_algorithm_Node_obj::iterator(){
            	HX_GC_STACKFRAME(&_hx_pos_7340535acf258a1e_178_iterator)
HXDLIN( 178)		return  ::haxe::ds::_GenericStack::GenericStackIterator_algorithm_Node_obj::__alloc( HX_CTX ,this->head);
            	}


HX_DEFINE_DYNAMIC_FUNC0(GenericStack_algorithm_Node_obj,iterator,return )

::String GenericStack_algorithm_Node_obj::toString(){
            	HX_STACKFRAME(&_hx_pos_7340535acf258a1e_203_toString)
HXLINE( 204)		::Array< ::Dynamic> a = ::Array_obj< ::Dynamic>::__new();
HXLINE( 205)		 ::haxe::ds::GenericCell_algorithm_Node l = this->head;
HXLINE( 206)		while(::hx::IsNotNull( l )){
HXLINE( 207)			a->push(l->elt);
HXLINE( 208)			l = l->next;
            		}
HXLINE( 210)		return ((HX_("{",7b,00,00,00) + a->join(HX_(",",2c,00,00,00))) + HX_("}",7d,00,00,00));
            	}


HX_DEFINE_DYNAMIC_FUNC0(GenericStack_algorithm_Node_obj,toString,return )


::hx::ObjectPtr< GenericStack_algorithm_Node_obj > GenericStack_algorithm_Node_obj::__new() {
	::hx::ObjectPtr< GenericStack_algorithm_Node_obj > __this = new GenericStack_algorithm_Node_obj();
	__this->__construct();
	return __this;
}

::hx::ObjectPtr< GenericStack_algorithm_Node_obj > GenericStack_algorithm_Node_obj::__alloc(::hx::Ctx *_hx_ctx) {
	GenericStack_algorithm_Node_obj *__this = (GenericStack_algorithm_Node_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(GenericStack_algorithm_Node_obj), true, "haxe.ds.GenericStack_algorithm_Node"));
	*(void **)__this = GenericStack_algorithm_Node_obj::_hx_vtable;
	__this->__construct();
	return __this;
}

GenericStack_algorithm_Node_obj::GenericStack_algorithm_Node_obj()
{
}

void GenericStack_algorithm_Node_obj::__Mark(HX_MARK_PARAMS)
{
	HX_MARK_BEGIN_CLASS(GenericStack_algorithm_Node);
	HX_MARK_MEMBER_NAME(head,"head");
	HX_MARK_END_CLASS();
}

void GenericStack_algorithm_Node_obj::__Visit(HX_VISIT_PARAMS)
{
	HX_VISIT_MEMBER_NAME(head,"head");
}

::hx::Val GenericStack_algorithm_Node_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 3:
		if (HX_FIELD_EQ(inName,"add") ) { return ::hx::Val( add_dyn() ); }
		if (HX_FIELD_EQ(inName,"pop") ) { return ::hx::Val( pop_dyn() ); }
		break;
	case 4:
		if (HX_FIELD_EQ(inName,"head") ) { return ::hx::Val( head ); }
		break;
	case 5:
		if (HX_FIELD_EQ(inName,"first") ) { return ::hx::Val( first_dyn() ); }
		break;
	case 6:
		if (HX_FIELD_EQ(inName,"remove") ) { return ::hx::Val( remove_dyn() ); }
		break;
	case 7:
		if (HX_FIELD_EQ(inName,"isEmpty") ) { return ::hx::Val( isEmpty_dyn() ); }
		break;
	case 8:
		if (HX_FIELD_EQ(inName,"iterator") ) { return ::hx::Val( iterator_dyn() ); }
		if (HX_FIELD_EQ(inName,"toString") ) { return ::hx::Val( toString_dyn() ); }
	}
	return super::__Field(inName,inCallProp);
}

::hx::Val GenericStack_algorithm_Node_obj::__SetField(const ::String &inName,const ::hx::Val &inValue,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 4:
		if (HX_FIELD_EQ(inName,"head") ) { head=inValue.Cast<  ::haxe::ds::GenericCell_algorithm_Node >(); return inValue; }
	}
	return super::__SetField(inName,inValue,inCallProp);
}

void GenericStack_algorithm_Node_obj::__GetFields(Array< ::String> &outFields)
{
	outFields->push(HX_("head",20,29,0b,45));
	super::__GetFields(outFields);
};

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo GenericStack_algorithm_Node_obj_sMemberStorageInfo[] = {
	{::hx::fsObject /*  ::haxe::ds::GenericCell_algorithm_Node */ ,(int)offsetof(GenericStack_algorithm_Node_obj,head),HX_("head",20,29,0b,45)},
	{ ::hx::fsUnknown, 0, null()}
};
static ::hx::StaticInfo *GenericStack_algorithm_Node_obj_sStaticStorageInfo = 0;
#endif

static ::String GenericStack_algorithm_Node_obj_sMemberFields[] = {
	HX_("head",20,29,0b,45),
	HX_("add",21,f2,49,00),
	HX_("first",30,78,9d,00),
	HX_("pop",91,5d,55,00),
	HX_("isEmpty",43,de,5f,0c),
	HX_("remove",44,9c,88,04),
	HX_("iterator",ee,49,9a,93),
	HX_("toString",ac,d0,6e,38),
	::String(null()) };

::hx::Class GenericStack_algorithm_Node_obj::__mClass;

void GenericStack_algorithm_Node_obj::__register()
{
	GenericStack_algorithm_Node_obj _hx_dummy;
	GenericStack_algorithm_Node_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("haxe.ds.GenericStack_algorithm_Node",09,d3,53,38);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &::hx::Class_obj::GetNoStaticField;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(0 /* sStaticFields */);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(GenericStack_algorithm_Node_obj_sMemberFields);
	__mClass->mCanCast = ::hx::TCanCast< GenericStack_algorithm_Node_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = GenericStack_algorithm_Node_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = GenericStack_algorithm_Node_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace haxe
} // end namespace ds
