// Generated by Haxe 4.3.1
#ifndef INCLUDED_haxe_ds_GenericCell_algorithm_Node
#define INCLUDED_haxe_ds_GenericCell_algorithm_Node

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS1(algorithm,Node)
HX_DECLARE_CLASS2(haxe,ds,GenericCell_algorithm_Node)

namespace haxe{
namespace ds{


class HXCPP_CLASS_ATTRIBUTES GenericCell_algorithm_Node_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef GenericCell_algorithm_Node_obj OBJ_;
		GenericCell_algorithm_Node_obj();

	public:
		enum { _hx_ClassId = 0x139ed92d };

		void __construct( ::algorithm::Node elt, ::haxe::ds::GenericCell_algorithm_Node next);
		inline void *operator new(size_t inSize, bool inContainer=true,const char *inName="haxe.ds.GenericCell_algorithm_Node")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,true,"haxe.ds.GenericCell_algorithm_Node"); }
		static ::hx::ObjectPtr< GenericCell_algorithm_Node_obj > __new( ::algorithm::Node elt, ::haxe::ds::GenericCell_algorithm_Node next);
		static ::hx::ObjectPtr< GenericCell_algorithm_Node_obj > __alloc(::hx::Ctx *_hx_ctx, ::algorithm::Node elt, ::haxe::ds::GenericCell_algorithm_Node next);
		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~GenericCell_algorithm_Node_obj();

		HX_DO_RTTI_ALL;
		::hx::Val __Field(const ::String &inString, ::hx::PropertyAccess inCallProp);
		::hx::Val __SetField(const ::String &inString,const ::hx::Val &inValue, ::hx::PropertyAccess inCallProp);
		void __GetFields(Array< ::String> &outFields);
		static void __register();
		void __Mark(HX_MARK_PARAMS);
		void __Visit(HX_VISIT_PARAMS);
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("GenericCell_algorithm_Node",b8,d4,ac,04); }

		 ::algorithm::Node elt;
		 ::haxe::ds::GenericCell_algorithm_Node next;
};

} // end namespace haxe
} // end namespace ds

#endif /* INCLUDED_haxe_ds_GenericCell_algorithm_Node */ 
