// Generated by Haxe 4.3.1
#ifndef INCLUDED_haxe_ds__GenericStack_GenericStackIterator_algorithm_Node
#define INCLUDED_haxe_ds__GenericStack_GenericStackIterator_algorithm_Node

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

#ifndef INCLUDED_cpp_FastIterator
#include <cpp/FastIterator.h>
#endif
HX_DECLARE_CLASS1(algorithm,Node)
HX_DECLARE_CLASS2(haxe,ds,GenericCell_algorithm_Node)
HX_DECLARE_CLASS3(haxe,ds,_GenericStack,GenericStackIterator_algorithm_Node)

namespace haxe{
namespace ds{
namespace _GenericStack{


class HXCPP_CLASS_ATTRIBUTES GenericStackIterator_algorithm_Node_obj : public ::cpp::FastIterator_obj<  ::algorithm::Node >
{
	public:
		typedef ::cpp::FastIterator_obj<  ::algorithm::Node > super;
		typedef GenericStackIterator_algorithm_Node_obj OBJ_;
		GenericStackIterator_algorithm_Node_obj();

	public:
		enum { _hx_ClassId = 0x35ed433b };

		void __construct( ::haxe::ds::GenericCell_algorithm_Node head);
		inline void *operator new(size_t inSize, bool inContainer=true,const char *inName="haxe.ds._GenericStack.GenericStackIterator_algorithm_Node")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,true,"haxe.ds._GenericStack.GenericStackIterator_algorithm_Node"); }
		static ::hx::ObjectPtr< GenericStackIterator_algorithm_Node_obj > __new( ::haxe::ds::GenericCell_algorithm_Node head);
		static ::hx::ObjectPtr< GenericStackIterator_algorithm_Node_obj > __alloc(::hx::Ctx *_hx_ctx, ::haxe::ds::GenericCell_algorithm_Node head);
		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~GenericStackIterator_algorithm_Node_obj();

		HX_DO_RTTI_ALL;
		::hx::Val __Field(const ::String &inString, ::hx::PropertyAccess inCallProp);
		::hx::Val __SetField(const ::String &inString,const ::hx::Val &inValue, ::hx::PropertyAccess inCallProp);
		void __GetFields(Array< ::String> &outFields);
		static void __register();
		void __Mark(HX_MARK_PARAMS);
		void __Visit(HX_VISIT_PARAMS);
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("GenericStackIterator_algorithm_Node",d2,51,c3,49); }

		 ::haxe::ds::GenericCell_algorithm_Node current;
		bool hasNext();

		 ::algorithm::Node next();

};

} // end namespace haxe
} // end namespace ds
} // end namespace _GenericStack

#endif /* INCLUDED_haxe_ds__GenericStack_GenericStackIterator_algorithm_Node */ 
