// Generated by Haxe 4.3.1
#include <hxcpp.h>

#ifndef INCLUDED_algorithm_Node
#include <algorithm/Node.h>
#endif
#ifndef INCLUDED_haxe_ds_GenericCell_algorithm_Node
#include <haxe/ds/GenericCell_algorithm_Node.h>
#endif
#ifndef INCLUDED_haxe_ds__GenericStack_GenericStackIterator_algorithm_Node
#include <haxe/ds/_GenericStack/GenericStackIterator_algorithm_Node.h>
#endif

HX_DEFINE_STACK_FRAME(_hx_pos_82f0dce6c1796a5a_78_new,"haxe.ds._GenericStack.GenericStackIterator_algorithm_Node","new",0xb0dfef2f,"haxe.ds._GenericStack.GenericStackIterator_algorithm_Node.new","/usr/local/lib/haxe/std/haxe/ds/GenericStack.hx",78,0xcaed4b39)
HX_LOCAL_STACK_FRAME(_hx_pos_82f0dce6c1796a5a_68_hasNext,"haxe.ds._GenericStack.GenericStackIterator_algorithm_Node","hasNext",0x342bd7bc,"haxe.ds._GenericStack.GenericStackIterator_algorithm_Node.hasNext","/usr/local/lib/haxe/std/haxe/ds/GenericStack.hx",68,0xcaed4b39)
HX_LOCAL_STACK_FRAME(_hx_pos_82f0dce6c1796a5a_71_next,"haxe.ds._GenericStack.GenericStackIterator_algorithm_Node","next",0x13115b44,"haxe.ds._GenericStack.GenericStackIterator_algorithm_Node.next","/usr/local/lib/haxe/std/haxe/ds/GenericStack.hx",71,0xcaed4b39)
namespace haxe{
namespace ds{
namespace _GenericStack{

void GenericStackIterator_algorithm_Node_obj::__construct( ::haxe::ds::GenericCell_algorithm_Node head){
            	HX_STACKFRAME(&_hx_pos_82f0dce6c1796a5a_78_new)
HXDLIN(  78)		this->current = head;
            	}

Dynamic GenericStackIterator_algorithm_Node_obj::__CreateEmpty() { return new GenericStackIterator_algorithm_Node_obj; }

void *GenericStackIterator_algorithm_Node_obj::_hx_vtable = 0;

Dynamic GenericStackIterator_algorithm_Node_obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< GenericStackIterator_algorithm_Node_obj > _hx_result = new GenericStackIterator_algorithm_Node_obj();
	_hx_result->__construct(inArgs[0]);
	return _hx_result;
}

bool GenericStackIterator_algorithm_Node_obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x35ed433b;
}

bool GenericStackIterator_algorithm_Node_obj::hasNext(){
            	HX_STACKFRAME(&_hx_pos_82f0dce6c1796a5a_68_hasNext)
HXDLIN(  68)		return ::hx::IsNotNull( this->current );
            	}


 ::algorithm::Node GenericStackIterator_algorithm_Node_obj::next(){
            	HX_STACKFRAME(&_hx_pos_82f0dce6c1796a5a_71_next)
HXLINE(  72)		 ::algorithm::Node result = this->current->elt;
HXLINE(  73)		this->current = this->current->next;
HXLINE(  74)		return result;
            	}



::hx::ObjectPtr< GenericStackIterator_algorithm_Node_obj > GenericStackIterator_algorithm_Node_obj::__new( ::haxe::ds::GenericCell_algorithm_Node head) {
	::hx::ObjectPtr< GenericStackIterator_algorithm_Node_obj > __this = new GenericStackIterator_algorithm_Node_obj();
	__this->__construct(head);
	return __this;
}

::hx::ObjectPtr< GenericStackIterator_algorithm_Node_obj > GenericStackIterator_algorithm_Node_obj::__alloc(::hx::Ctx *_hx_ctx, ::haxe::ds::GenericCell_algorithm_Node head) {
	GenericStackIterator_algorithm_Node_obj *__this = (GenericStackIterator_algorithm_Node_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(GenericStackIterator_algorithm_Node_obj), true, "haxe.ds._GenericStack.GenericStackIterator_algorithm_Node"));
	*(void **)__this = GenericStackIterator_algorithm_Node_obj::_hx_vtable;
	__this->__construct(head);
	return __this;
}

GenericStackIterator_algorithm_Node_obj::GenericStackIterator_algorithm_Node_obj()
{
}

void GenericStackIterator_algorithm_Node_obj::__Mark(HX_MARK_PARAMS)
{
	HX_MARK_BEGIN_CLASS(GenericStackIterator_algorithm_Node);
	HX_MARK_MEMBER_NAME(current,"current");
	HX_MARK_END_CLASS();
}

void GenericStackIterator_algorithm_Node_obj::__Visit(HX_VISIT_PARAMS)
{
	HX_VISIT_MEMBER_NAME(current,"current");
}

::hx::Val GenericStackIterator_algorithm_Node_obj::__Field(const ::String &inName,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 4:
		if (HX_FIELD_EQ(inName,"next") ) { return ::hx::Val( next_dyn() ); }
		break;
	case 7:
		if (HX_FIELD_EQ(inName,"current") ) { return ::hx::Val( current ); }
		if (HX_FIELD_EQ(inName,"hasNext") ) { return ::hx::Val( hasNext_dyn() ); }
	}
	return super::__Field(inName,inCallProp);
}

::hx::Val GenericStackIterator_algorithm_Node_obj::__SetField(const ::String &inName,const ::hx::Val &inValue,::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 7:
		if (HX_FIELD_EQ(inName,"current") ) { current=inValue.Cast<  ::haxe::ds::GenericCell_algorithm_Node >(); return inValue; }
	}
	return super::__SetField(inName,inValue,inCallProp);
}

void GenericStackIterator_algorithm_Node_obj::__GetFields(Array< ::String> &outFields)
{
	outFields->push(HX_("current",39,9c,e3,cb));
	super::__GetFields(outFields);
};

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo GenericStackIterator_algorithm_Node_obj_sMemberStorageInfo[] = {
	{::hx::fsObject /*  ::haxe::ds::GenericCell_algorithm_Node */ ,(int)offsetof(GenericStackIterator_algorithm_Node_obj,current),HX_("current",39,9c,e3,cb)},
	{ ::hx::fsUnknown, 0, null()}
};
static ::hx::StaticInfo *GenericStackIterator_algorithm_Node_obj_sStaticStorageInfo = 0;
#endif

static ::String GenericStackIterator_algorithm_Node_obj_sMemberFields[] = {
	HX_("current",39,9c,e3,cb),
	HX_("hasNext",6d,a5,46,18),
	HX_("next",f3,84,02,49),
	::String(null()) };

::hx::Class GenericStackIterator_algorithm_Node_obj::__mClass;

void GenericStackIterator_algorithm_Node_obj::__register()
{
	GenericStackIterator_algorithm_Node_obj _hx_dummy;
	GenericStackIterator_algorithm_Node_obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("haxe.ds._GenericStack.GenericStackIterator_algorithm_Node",bd,2b,f7,3c);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &::hx::Class_obj::GetNoStaticField;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(0 /* sStaticFields */);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(GenericStackIterator_algorithm_Node_obj_sMemberFields);
	__mClass->mCanCast = ::hx::TCanCast< GenericStackIterator_algorithm_Node_obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = GenericStackIterator_algorithm_Node_obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = GenericStackIterator_algorithm_Node_obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace haxe
} // end namespace ds
} // end namespace _GenericStack
